baseURL: "https://thesoundofaiosr.github.io/"
languageCode: "en-us"
title: "The Sound Of AI - Open source Research"
theme: "book"

markup:
  goldmark:
    renderer:
      unsafe: true

  tableOfContents:
    startLevel: 1

params:
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme: 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC: true
